import { useState, useEffect, FC, ReactElement } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Viewer } from '../components/builder/viewer'
import { TaskItemResponse } from '../interface'
import { data } from '../data/practice'
// import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [practice, setPractice] = useState<TaskItemResponse>(data.item)

  const handleFinishClick = () => {
    window.history.back()
  }

  if(!practice) return null;

  // console.log('Viewer', Viewer);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="account-app">
        <Viewer
          defaultQuestionTitle={'Task'}
          practice={practice}
          mode={'anonymous'}
          // sessionId={sessionId}
          // onFinishClick={handleFinishClick}
        />
      </main>
    </>
  )
}

export default Home
